font_family Inter
font_size 16.0

background {{ .colors.surface }}
foreground {{ .colors.on_surface }}

cursor {{ .colors.primary }}
cursor_text_color {{ .colors.on_primary }}

selection_background {{ .colors.secondary_container }}
selection_foreground {{ .colors.on_secondary_container }}

# Black
color0 {{ .colors.surface_variant }}
color8 {{ .colors.on_surface_variant }}

# Red
color1 {{ .colors.error }}
color9 {{ .colors.error_container }}

# Green
color2 {{ .colors.tertiary }}
color10 {{ .colors.tertiary_container }}

# Yellow
color3 {{ .colors.secondary }}
color11 {{ .colors.secondary_container }}

# Blue
color4 {{ .colors.primary }}
color12 {{ .colors.primary_container }}

# Magenta
color5 {{ .colors.tertiary }}
color13 {{ .colors.tertiary_container }}

# Cyan
color6 {{ .colors.secondary }}
color14 {{ .colors.secondary_container }}

# White
color7 {{ .colors.on_surface }}
color15 {{ .colors.surface }}
